---
- name: Provision baseline configs
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: OBTAIN LOGIN CREDENTIALS
      include_vars: creds.yaml

- name: Provision PE routers baseline configs
  hosts: pe_routers
  connection: local
  gather_facts: no
  roles:
    - base_config
    - pe_routers

- name: Provision P routers baseline configs
  hosts: p_routers
  connection: local
  gather_facts: no
  roles:
    - base_config
    - p_routers

- name: Provision RR router baseline configs
  hosts: rr_router
  connection: local
  gather_facts: no
  roles:
    - base_config
    - rr_router
