---
- name: Provision P routers baseline configs
  hosts: p_routers
  connection: local
  gather_facts: no
  roles:
    - base_config
    - p_routers

- name: Provision PE routers baseline configs
  hosts: pe_routers
  connection: local
  gather_facts: no
  roles:
    - base_config
    - pe_routers

- name: Provision RR router baseline configs
  hosts: rr_router
  connection: local
  gather_facts: no
  roles:
    - base_config
    - rr_router

- name: Provision CE routers baseline configs
  hosts: ce_routers
  connection: local
  gather_facts: no
  roles:
    - ce_routers
