---
# This is the file that will define all of the IP 
# addressing and device interface numbering

host: 
    name: ce1
    loopback: 
      ip: 192.168.10.255

interfaces:
  - name: ge-0/0/1
    description: VPLS Link
    ip: 192.168.100.1
    mask: 24
  - name: ge-0/0/2
    description: Link to EH1
    ip: 192.168.10.1
    mask: 25
  - name: ge-0/0/3
    description: Link to EH2
    ip: 192.168.10.129
    mask: 25  