---
# This is the file that will define all of the IP 
# addressing and device interface numbering

host: 
    name: ce6
    loopback: 
      ip: 192.168.60.255

interfaces:
  - name: ge-0/0/1
    description: LINK to PE3
    ip: 192.168.255.7
    mask: 31
  - name: ge-0/0/2
    description: Link to EH8
    ip: 192.168.60.1
    mask: 25
  - name: ge-0/0/3
    description: Link to EH9
    ip: 192.168.60.129
    mask: 25  
