---
# This is the file that will define all of the IP 
# addressing and device interface numbering

host: 
    name: p2
    loopback: 
      ip: 192.168.0.2
      ipv6: 2001:192:168:0::2
      iso: 49.0001.0192.0168.0002.00
      asn: 65000

interfaces:
  - name: ge-0/0/1
    description: Link to P1
    ip: 192.168.1.5
    peer: 192.168.1.4
    mask: 31
  - name: ge-0/0/2
    description: Link to PE2
    ip: 192.168.1.10
    peer: 192.168.1.11
    mask: 31
  - name: ge-0/0/3
    description: Link to P£4
    ip: 192.168.1.12
    peer: 192.168.1.13
    mask: 31

